openapi: "3.0.0"
info:
  title: "Sample API"
  description: "Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML."
servers:
  - url: "http://localhost:9000"
    description: "Optional server description, e.g. Main (production) server"
